### ISSUE TITLE
Pass arguments to mapArray

### ISSUE THREAD

**Issue by jneuendorf** [sindresorhus/map-obj#16]
Hey, 

I just looked through your code to see if your package does what I need.
This library could consume less memory (I think) by moving `mapArray` out of `mapObj` and pass the arguments along - just like you pass them into `mapObj`.
Currently a new function is created for each recursive call. For big objects that might be quite some memory, I guess.

**Comment by sindresorhus** [comment]
Hard to say. It really depends on how smart V8 and other JS engines are. I try to not make assumptions as they're often wrong when it comes to JIT'd code. Better to work based on evidence. Since there's no evidence here, I prefer to keep it as is as it's more readable. Thanks for the suggestion though.
